library(Seurat)
args <- commandArgs(T)
indata <- args[1]
data <- Read10X(data.dir = indata)
scRNA <- CreateSeuratObject(data,project = "scRNA",min.cells = 3)
scRNA <- subset(scRNA,subset = nFeature_RNA < 6500 & nFeature_RNA > 650)
scRNA <- NormalizeData(scRNA,normalization.method = "LogNormalize")
scRNA <- FindVariableFeatures(scRNA,selection.method = "mvp")
scRNA <- ScaleData(scRNA,features = rownames(scRNA))
scRNA <- RunPCA(scRNA,npcs = 100)
scRNA <- FindNeighbors(scRNA,dims = 1:50)
scRNA <- FindClusters(scRNA,resolution = 0.5)
scRNA <- RunTSNE(scRNA, dims = 1:50)
scRNA <- RunUMAP(scRNA, dims = 1:50)
saveRDS(scRNA,file = "pgDQ_scRNA.rds")